### PR TITLE
Usage of OpenLDAP 2.4 LDIF configuration instead of configfiles

### PR DESCRIPTION
**Pull request by abehling**
First try to make new configuration (LDIF based) model work.

Minor beauty change: Moved pillar configuration to openldap::lookup because this dict is merged in the map.jinja. 

- Tested with CentOS 7

### CODE REVIEW

**Comment by 0xf10e** [comment]
You misunderstood the purpose of the lookup pillar: It's there to override defaults for platform specific parameters like package names. Like when you add a backport repo to your Debian and want to use `mariadb-server-12` instead of `mariadb-server` which provides version 10.

**Comment by abehling** [comment]
Hmmm... I don't think I misunderstood. It is best practice to organize **all** formula related pillar data under the second level 'lookup' pillar, at least this is stated in  https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#organizing-pillar-data . But OK, I can revert these changes. Anything else I should take care of?

**Comment by 0xf10e** [comment]
Yeah, "formula-related" is the keyword here. Take a look at the [zabbix-formula's `pillar.example`](https://github.com/saltstack-formulas/zabbix-formula/blob/master/pillar.example).
It's good you've used a pillar key to switch to the LDIF-based configuration. Though `openldap.ng` doesn't tell anyone what it will do. 
You also should make `README.rst` and `pillar.example` reflect your changes.

Oh, and why did you remove a schema from the RedHat section of `map.jinja` in  8b55c8d? It's not mentioned in the commit message.

Maybe you can just cherrypick 974a8b75 and 8b55c8d to keep the commit log cleaner instead of adding and removing things in the same PR?

**Comment by abehling** [comment]
OK, now that I had time to test some other distributions this is a bit premature. I will close the PR since the code needs more work to do. All major distributions use OpenLDAP 2.4 now which marks slapd.conf as deprecated so in my opinion the LDIF approach is the right way to go. @0xf10e Thank you for your time, anyway. Either I will come back with a more mature (and presumably bigger) PR or I will write a completely new formula from scratch. :-)

**Pull request closed without merging**
